services:
  database:
    image: postgres:latest
    container_name: linkhub-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}
    volumes:
      - linkhub-db-data:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  linkhub-db-data:
